<?php
session_start();
date_default_timezone_set('Africa/Johannesburg');
include 'includes/db.php';

if (!isset($_SESSION['user_id']) || !in_array($_SESSION['role'], ['finance','admin','principal','treasurer'])) {
    header("Location: login.php");
    exit;
}

$year = isset($_GET['year']) ? (int)$_GET['year'] : (int)date('Y');

$totalRequisitions = $conn->query("SELECT COUNT(*) AS c FROM requisitions WHERE YEAR(created_at) = $year")->fetch_assoc()['c'];
$totalPaidAmount = $conn->query("SELECT COALESCE(SUM(amount),0) AS s FROM requisitions WHERE status='Paid' AND YEAR(created_at) = $year")->fetch_assoc()['s'];
$totalBudget = $conn->query("SELECT COALESCE(SUM(budget_amount),0) AS s FROM department_budgets WHERE budget_year = $year")->fetch_assoc()['s'];

// Prefer history if archived
$hist = $conn->query("SELECT * FROM department_budget_history WHERE budget_year = $year ORDER BY department");
$useHistory = $hist && $hist->num_rows > 0;

if (!$useHistory) {
    $rows = $conn->query("
        SELECT b.department, b.budget_amount,
            COUNT(r.id) AS total_requisitions,
            SUM(CASE WHEN r.status='Paid' THEN 1 ELSE 0 END) AS paid_count,
            COALESCE(SUM(CASE WHEN r.status='Paid' THEN r.amount ELSE 0 END),0) AS amount_spent
        FROM department_budgets b
        LEFT JOIN requisitions r ON r.department = b.department AND YEAR(r.created_at) = $year
        WHERE b.budget_year = $year
        GROUP BY b.department, b.budget_amount
        ORDER BY b.department
    ");
}
?>
<!DOCTYPE html>
<html>
<head>
    <title>Budget Report <?= $year ?></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body { font-family: Arial, sans-serif; color:#111; }
        h1,h2,h3 { color:#0B1D39; }
        table { width:100%; border-collapse:collapse; margin-top:12px; }
        th { background:#0B1D39; color:#fff; padding:10px; text-align:left; }
        td { padding:9px; border-bottom:1px solid #ddd; }
        .spent { color:#dc3545; font-weight:bold; }
        .remain { color:#198754; font-weight:bold; }
        .over { color:#dc3545; font-weight:bold; }
        @media print {
            .no-print { display:none !important; }
        }
    </style>
</head>
<body class="p-4">
    <div class="no-print mb-3">
        <button onclick="window.print()" class="btn btn-primary">Print / Save as PDF</button>
        <a href="reports.php" class="btn btn-secondary">Back</a>
    </div>

    <h1>Midrand Primary School</h1>
    <h2>Annual Budget & Requisition Report — <?= $year ?></h2>
    <p>Generated: <?= date('d M Y H:i') ?> | Generated by: <?= htmlspecialchars($_SESSION['full_name'] ?? '') ?></p>

    <h3>Summary</h3>
    <ul>
        <li>Total requisitions (<?= $year ?>): <strong><?= (int)$totalRequisitions ?></strong></li>
        <li>Total budget allocation: <strong>R<?= number_format((float)$totalBudget, 2) ?></strong></li>
        <li>Total amount spent (Paid): <strong class="spent">R<?= number_format((float)$totalPaidAmount, 2) ?></strong></li>
        <li>Total remaining: <strong class="remain">R<?= number_format((float)($totalBudget - $totalPaidAmount), 2) ?></strong></li>
    </ul>

    <h3>Department Breakdown</h3>
    <table>
        <thead>
            <tr>
                <th>Department</th>
                <th>Total Reqs</th>
                <th>Paid Reqs</th>
                <th>Initial Budget</th>
                <th>Spent</th>
                <th>Remaining</th>
            </tr>
        </thead>
        <tbody>
        <?php if ($useHistory): while ($row = $hist->fetch_assoc()): ?>
            <tr>
                <td><?= htmlspecialchars($row['department']) ?></td>
                <td><?= (int)$row['total_requisitions'] ?></td>
                <td><?= (int)$row['paid_count'] ?></td>
                <td>R<?= number_format((float)$row['budget_amount'], 2) ?></td>
                <td class="spent">R<?= number_format((float)$row['amount_spent'], 2) ?></td>
                <td class="<?= $row['remaining'] < 0 ? 'over' : 'remain' ?>">R<?= number_format((float)$row['remaining'], 2) ?></td>
            </tr>
        <?php endwhile; else: while ($row = $rows->fetch_assoc()):
            $rem = $row['budget_amount'] - $row['amount_spent'];
        ?>
            <tr>
                <td><?= htmlspecialchars($row['department']) ?></td>
                <td><?= (int)$row['total_requisitions'] ?></td>
                <td><?= (int)$row['paid_count'] ?></td>
                <td>R<?= number_format((float)$row['budget_amount'], 2) ?></td>
                <td class="spent">R<?= number_format((float)$row['amount_spent'], 2) ?></td>
                <td class="<?= $rem < 0 ? 'over' : 'remain' ?>">R<?= number_format((float)$rem, 2) ?></td>
            </tr>
        <?php endwhile; endif; ?>
        </tbody>
    </table>

    <p class="mt-4"><em>End of report. Keep this PDF for audit and SGB records.</em></p>
</body>
</html>